### ISSUE TITLE
 Error: Invariant failed -> In Remix project

### ISSUE THREAD

**Issue by netdesignr** [alexreardon/tiny-invariant#146]
Hi,

I'm facing this error during Github Action CI, can someone please advice?

```
> start:mocks
> binode --require ./mocks -- @remix-run/serve:remix-serve build

🔶 Mock server running

/home/runner/work/project-name/tproject-namenode_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10
        throw new Error(prefix);
              ^
Error: Invariant failed
    at invariant (/home/runner/work/project-name/project-name/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10:15)
    at Object.<anonymous> (/home/runner/work/project-name/project-name/build/index.js:124:35)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/project-name/project-name/node_modules/@remix-run/serve/dist/cli.js:48:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
http://localhost:8811 timed out on retry 91 of 3, elapsed 90246ms, limit 90000ms
Error: connect ECONNREFUSED 127.0.0.1:8811
```

Any thoughts on the above?

Thanks a lot!

**Comment by SMysakowski** [comment]
The same story..

**Comment by pkerschbaum** [comment]
Could you provide a minimal reproduction?  
Then I would look into this :)

**Comment by alexreardon** [comment]
I will close this issue for now. Please feel free to reopen if this is still an issue

**Comment by alexreardon** [comment]
I will close this issue for now. Please feel free to reopen if this is still an issue

**Comment by mdingena** [comment]
@alexreardon This is still happening in Remix 1.7.2 with tiny-invariant 1.3.1.

**Comment by pkerschbaum** [comment]
@mdingena could you please provide a minimal reproduction?  
Then I would look into that.

**Comment by SMysakowski** [comment]
> @mdingena could you please provide a minimal reproduction? Then I would look into that.

You can just try e.g this stack https://github.com/remix-run/indie-stack. You will see the error when Github Action in Cypress job tries to build App.

![image](https://user-images.githubusercontent.com/24304415/200951852-ef2a0b62-fb9f-450a-9187-a45034b12f76.png)

**Comment by alexreardon** [comment]
@pkerschbaum would you be open to taking a look?

**Comment by hawkup** [comment]
I found the problem also. But I forgot to set secret environment on `fly.io`. Remix use tiny-variant to validate env value.
```js
(0, import_tiny_invariant.default)(process.env.SESSION_SECRET, "SESSION_SECRET must be set");
```
---


If you didn't set the environment and use indie stack. this is the command to set env
```cmd
flyctl secrets set DATABASE_URL="{your db url}"              #example "file:./data.db?connection_limit=1"
flyctl secrets set SESSION_SECRET="{your secret}"            #example "super-duper-s3cret"
```
doc: https://fly.io/docs/reference/secrets/#setting-secrets

After set these 2 config, the deployment was success.

**Comment by SMysakowski** [comment]
> I found the problem also. But I forgot to set secret environment on `fly.io`. Remix use tiny-variant to validate env value.
> 
> ```js
> (0, import_tiny_invariant.default)(process.env.SESSION_SECRET, "SESSION_SECRET must be set");
> ```
> 
> If you didn't set the environment and use indie stack. this is the command to set env
> 
> ```batchfile
> flyctl secrets set DATABASE_URL="{your db url}"              #example "file:./data.db?connection_limit=1"
> flyctl secrets set SESSION_SECRET="{your secret}"            #example "super-duper-s3cret"
> ```
> 
> doc: https://fly.io/docs/reference/secrets/#setting-secrets
> 
> After set these 2 config, the deployment was success.

Hi @hawkup :)   
  
In my case, it is not connected with fly deployment because I have already deployed the app.   
  
But I took a closer look at deploy.yml prepared by Indie stack. I rewrote the part which was preparing `.env` for cypress job, and it works.  
  
IMO ticket to close. It was strictly connected with the GitHub Actions configuration in the Remix template.

**Comment by pkerschbaum** [comment]
I would suggest to close this issue as it is just an invariant failing in the remix-run/indie-stack project.

**Comment by konotorii** [comment]
this is also happening with the remix-run/blues-stack with absolutely no changes to any of the files.

still happening with remix 1.7.5 and tiny-invariant 1.3.1

**Comment by pkerschbaum** [comment]
@konotorii I guess you get an `Error: Invariant failed`.  
That means remix-run/blues-stack asserts something using this library tiny-invariant, and that assertion fails.  
I would guess that something in the setup went wrong, as it was the case for some other folks (see comments above).

**Comment by konotorii** [comment]
the issue was i didnt run ```npm run setup``` which im guessing the others didnt as well
